version: "3.9"

services:
  app:
    container_name: concerts-api-app
    build:
      context: ./concerts-api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./concerts-api:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: concerts_db
      DB_USERNAME: root
      DB_PASSWORD: password

  db:
    container_name: concerts-api-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: concerts_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


